import type { Metadata } from "next";
import { Hind, Roboto, Montserrat} from "next/font/google";
import "./globals.css";

const hind = Hind({ weight: ['300', '400', '500' , '600', '700'], subsets:['latin'], variable: '--font-hind' });
const roboto = Roboto({ weight: ['300', '400', '500', '700'], subsets:['latin'], variable: '--font-roboto' });
const montserrat = Montserrat({ weight: ['300', '400', '500' , '600', '700'], subsets:['latin'], variable: '--font-montserrat' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hind.variable} ${roboto.variable} ${montserrat.variable}`}>{children}</body>
    </html>
  );
}
